name: Build unsigned APK (modifiable-action-and-data)

on:
  push:
    branches:
      - 'modifiable-action-and-data'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'
    #- name: Prepare Android keystore
    #  run: echo ${{ secrets.ENCODEDKEYSTORE }} | base64 --decode > ActivityLauncherApp/keystore.jks
    - name: Download dependencies
      run: ./gradlew androidDependencies
    - name: Build release APK
      run: ./gradlew assembleRelease
    #  env:
    #    KEYSTORE: keystore.jks
    #    KEYSTORE_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
    #    KEY_ALIAS: ${{ secrets.KEYALIAS }}
    #    KEY_PASSWORD: ${{ secrets.KEYPASSWORD }}
    - name: Upload release APK
      uses: actions/upload-artifact@v2
      with:
        name: release.apk
        path: ActivityLauncherApp/build/outputs/apk/release/ActivityLauncherApp-release.apk
